travis:
  secure:
    BINSTAR_TOKEN: wGODlnPNIbo4cxMYNosmpHxKJQ9rp8xqCpaaUFWMptIWcpF2TEhkq3vXQXmq0shm1fgQ8Xx/SX3lFrESrbnFjjYi0G/gR6usD4dYLaFYfNsYI9uK0Xl9jVg7983op5ELLiP+qdvsHH+eunCVAQRUvl2wQoXEXHzrqBF9wj1xS3C4rcvnloPmH+1s/6tjFanQo44dkXFAivKFlFet7QED+YHkU0k8sDGU82PAKjvPD80mbyV8MvgUBR26rWvdALA8f+4zfK0kRhdD84QKGOUjdqMDsxICcqphdhI1t6z+IUJGcWQ1PhHuQJVFFqW399ZvWHZPmwQoNRetUSXO9EEB64+vnaDYX1Ji6GcQ20G9lP6KuXDBongaLUvYHQRbLVzZH5cHNQBwTGLu7SjzKUbYZczWtw4MBIDf1EoxQbaK14wjF3z4rL4sKAGuVwEkRggiihJQFHVPm5cRBrzoOaDol2GAtK/HzT1bNXkfsUwpqmcEY7FNus8MCFNu5v2pNehps16ovGwbj6gZj+j/8JnFFXLBanMASJvLqbKeHcOOljvR9q3eu/aQQYtLZihUOi/VqN8sMWChxHku9jvyhV+LRyBA49TzwTWWLAvdOTFiEZlVTTJaI/7YN315npIG0QGW93X5Y54jGsjUjoG2bWbs+QMhaUkLczM+TKCic/EkI/8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
