travis:
  secure:
    BINSTAR_TOKEN: JAsD9VsOVdmYLaFL4CjyNZCD094E2OQSTpufGtgYlBBvS9kPTL08OlBIwXjTNiSxyfLUSwUep9Log14v8kvkFvXFvNasguyKCiO/FL//ouNp518mU8iNZEUnIEkc7auPQvMEci43LGvF6du2RIHNlMphkNffLbc9ibH60F/FSHfBbRXD1EzVyVmS1S3xphEsZR1hC0SqN3jucC8vMKHYHvu/v19QYiYLn8qEhNbBtOcL1SY6IXi86Sp/592/M4wUzQgccJHAE+HBFSFvpv1j80V5oQ4ri/iuf63xXl3qVkeBePRgLFdxdb4c/8DpUJYcbOM0/GwbXxmHvQoe3B1MMx585DIt6ymsV5n7FjthIVz04nEsj9KHuucBkI/GCARmqdxDAXmoj1vXAQkxuHdLN7KKbW+Og1x7Y+17ThTrWfFCEL4FM+wmwSnIPHnQE+mA8NZ7QHTXtWqLI21rj0DWHNHYOBKp/JLp+C78QBe/fDqzyvkyG1tdV+BdSkzL7EBZpvOo0gJOlCcqPc7ob/SErifsjAQJTtxZCqdOTKCdiCwChel0hV1H0jiTWZyZKP4vDHUMFg7U1QXC3a9w5P9GvhNwBAUvKtWlmvasdmTdJHy690ry95eqaaW95WBzO10/C1q/D2CGBVxgKAcbkde//T7hF/bIqOPZJVIlbR4naUE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
