travis:
  secure:
    BINSTAR_TOKEN: XO1GPoQLwTR5tVVWYPvp6XvljM4rrYL1cnVZ7FZqWdYqGB2LyJjn8KmY18CGgnbU2S99kTwOryN8tqQbDY6ebBIlZYr3rXlOnUEaQxBgZRUBTKSzxAoqJJ0HGkHbt2/6CoUsEYAHN6vknAqV+c4HIJGdAog3raMfaMQZ6Lsa0Hq292bRdKCo0tY0Pie7yPXon+C8GmMBlE4odq5nRp9SJu4xLhi2ZNjeMFDvkzTwbpWEh/c+gptrckEDvR8bHGoFSKOtT/LH73Zz+Kck7YIFf2srQERvJ4niFNrYRvMwlwbfv0JwDoNDQHywC0Wry+3KSR6xSN996jte+yYcpNhQmKXA2FmTi4Fk+NJSIZ4qQGa+x3KjqcFwvghaPuCnH9fh2RbekmY3SsePTiJjpQyzSnj4q1Tm3DjpXW4UG8+cKj/gBtM510U+AI7rZrwvj/V9AQqfhsT3PWhN5sj4jXhNhUjITL11EHlPwHTqxiGoDikqXfKGrQvL9nuXieEIgpsPDlkU1DfUChCi0pVHWM7Zl+Akh+eWv1ife86o+22IcRufbDYZFJ04rQLS+p/MdX5XzKZ3FQE1CAMbzRYCLiIPD6aknmVwp15JW9ABdOgKJfCALrBYS984tYZ5ZYANdpVmdzcgtbZK2ta7ygyhdP+p74qfjdpX/UTwpH5rgmthS+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
