travis:
  secure:
    BINSTAR_TOKEN: XdrWOklCWNobhy3jKbORF96yp7NyfhhdF0letfnjJJ4Va7mrx1bRtGVA1yOAHiE+qx8uQkvHQ653OklZjmUKJqNPVLR6OVDrpHm+6EFEfzwvYMPAcsG3UT8Km9D4Mq4sT0SBw9b4HxuCQp7Bf6zrLlGJWWanKq48cZfxuHg3CGM95u0YtkkFqdHwiF0+rB4Zu1gWuxYD7kx93Qo5lp9xaeG0ynorR2K1kECwUzFOgp1BcP4t2o4zuwkI8G/ilbNWGXO/FN9Mr9qIsmf41jqwDGyj6F0x4XZPbN/Qkh7Zjwp6FIjtci5luMYTqo0SNU85uAMgahjVsLzCW9DfV2pQbx9O+vthlCW+dyIJD99aWI2NByCJQs9DvLnrOOp6uqFBarOFBJIRR4B4s8NYiFO1H7Jpbb8jPe6uv8SWNcUy5YlPD47r81z7h61WE8668Raqk6F+CAz/XHL9yyVyPKOMZfEkYJhQvAz9lA5cORlakkrXdDn/VfQlwWFbQ+MvfHRipuFJhXxMhIuSUbHvjGJwabdvy7F/iAgtndRvMK1jMwVU7+LItO0o7bgQiFmHfwC/acG1ubNJd1ElrIQ+gYzhxJxLtxHKTZfBTmYdDIumxsZSTOF5o2nRipzZ95VG7XfjrACHEfJ9fqiQ8OUdupLAKDXuunw2/oD3tWtRvBa1+iQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
